"""Add deleted column to all table

Revision ID: f9bf49fa4b6c
Revises: 2735bb0547af
Create Date: 2025-04-06 11:03:01.225304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bf49fa4b6c'
down_revision: Union[str, None] = '2735bb0547af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('book_author', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('book_user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('profile', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.drop_column('profile', 'deleted')
    op.drop_column('books', 'deleted')
    op.drop_column('book_user', 'deleted')
    op.drop_column('book_author', 'deleted')
    op.drop_column('authors', 'deleted')
    # ### end Alembic commands ###
